Repository arncv/Intima, pull requests merged in 2023-10, with the labels that each got.

#13 Added a Dark Mode option on home page but it works on double-click
  package-lock.json
  package.json
  public/css/styles.css
  public/index.html
  public/js/dark-script.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#49 add open popup link button
  public/css/styles.css
  public/index.html
  public/scripts.js
Labels: hacktoberfest, hacktoberfest-accepted

#78 Improved Check Your Knowledge Button
  public/index.html
Labels: hacktoberfest-accepted

#82 -Redesigned the quiz ui -Updated the nodemon dependencies in the serv…
  package-lock.json
  package.json
  public/pages/quiz.css
  public/pages/quiz.html
Labels: hacktoberfest-accepted

#85 Solved - Share is not working in some Modals. #84
  public/index.html
  public/scripts.js
Labels: hacktoberfest, hacktoberfest-accepted

#97 UI updated
  public/pages/quiz.css
  public/pages/quiz.html
Labels: hacktoberfest-accepted
